name: Build

on:
  push:
    branches: main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build action
        run: yarn build

      - name: Commit dist
        uses: EndBug/add-and-commit@v9
        with:
          add: dist
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "[auto] Update dist/index.js"
